### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by paulmueller** [RI-imaging/DryMass#31]
i.e. compile bhfield for macOS

https://github.com/RI-imaging/DryMass/runs/2252081619?check_suite_focus=true

**Comment by samuel424** [comment]
Hello! 
It would be nice if you guys also supported MacOS, there is a problem with qpsphere on MAC. 


Building wheels for collected packages: qpsphere
  Building wheel for qpsphere (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [41 lines of output]
      /Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      NumExpr defaulting to 4 threads.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/setup.py", line 26, in <module>
          setup(
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/setup.py", line 21, in run
          download_binaries(package_dir=True)
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/qpsphere/util.py", line 36, in download_binaries
          paths = fetch_bhfield.get_binaries()
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/qpsphere/models/_bhfield/fetch.py", line 115, in get_binaries
          paths.append(get_binary(arp=arp))
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/qpsphere/models/_bhfield/fetch.py", line 84, in get_binary
          dl_root = get_download_root()
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/qpsphere/models/_bhfield/fetch.py", line 78, in get_download_root
          raise BinaryNotAvailableError(msg)
      qpsphere.models._bhfield.fetch.BinaryNotAvailableError: BHFIELD currently unavailable for platform 'Darwin'!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for qpsphere
  Running setup.py clean for qpsphere
Failed to build qpsphere
Installing collected packages: qpsphere, qpformat, drymass
  Running setup.py install for qpsphere ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for qpsphere did not run successfully.
  │ exit code: 1
  ╰─> [45 lines of output]
      /Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running install
      /Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      NumExpr defaulting to 4 threads.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/setup.py", line 26, in <module>
          setup(
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/command/install.py", line 68, in run
          return orig.install.run(self)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/command/install.py", line 698, in run
          self.run_command('build')
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/Users/samuelzargani/opt/anaconda3/envs/snowflakes/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/setup.py", line 21, in run
          download_binaries(package_dir=True)
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/qpsphere/util.py", line 36, in download_binaries
          paths = fetch_bhfield.get_binaries()
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/qpsphere/models/_bhfield/fetch.py", line 115, in get_binaries
          paths.append(get_binary(arp=arp))
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/qpsphere/models/_bhfield/fetch.py", line 84, in get_binary
          dl_root = get_download_root()
        File "/private/var/folders/d3/vwp3_6jx21g29t42v17nqg_c0000gn/T/pip-install-7uoseney/qpsphere_dbd30acab93d419992bf3c827ecf95e7/qpsphere/models/_bhfield/fetch.py", line 78, in get_download_root
          raise BinaryNotAvailableError(msg)
      qpsphere.models._bhfield.fetch.BinaryNotAvailableError: BHFIELD currently unavailable for platform 'Darwin'!
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> qpsphere

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
